import {
  BarChart3,
  Building2,
  Calculator,
  CreditCard,
  IndianRupee,
  FileBarChart2,
  LayoutDashboard,
  ListOrdered,
  Receipt,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Users,
  WalletCards,
  Landmark,
} from "lucide-react";

export const navigationByRole = {
  student: [
    { label: "Overview", to: "/student", icon: LayoutDashboard },
    { label: "Bills", to: "/student/bills", icon: Receipt },
    { label: "Payments", to: "/student/payments", icon: CreditCard },
    { label: "EBL Status", to: "/student/ebl", icon: ShieldCheck },
  ],
  caretaker: [
    { label: "Overview", to: "/caretaker", icon: LayoutDashboard },
    { label: "Consumption", to: "/caretaker/consumption", icon: ListOrdered },
    { label: "Guest Charge", to: "/caretaker/guest-charge", icon: Users },
    { label: "Static Charges", to: "/caretaker/charges", icon: Sparkles },
    { label: "Hostel Expense", to: "/caretaker/hostel-expense", icon: Calculator },
    { label: "EBL Claims", to: "/caretaker/ebl", icon: ShieldCheck },
    { label: "Advances", to: "/caretaker/advances", icon: Landmark },
    { label: "Expenses", to: "/caretaker/expenses", icon: IndianRupee },
    { label: "Bills", to: "/caretaker/bills", icon: Receipt },
    { label: "Mess Bill / Student", to: "/caretaker/mess-bill-per-student", icon: ScrollText },
    { label: "Payments", to: "/caretaker/payments", icon: WalletCards },
    { label: "Reports", to: "/caretaker/reports", icon: ScrollText },
  ],
  admin: [
    { label: "Overview", to: "/admin", icon: LayoutDashboard },
    { label: "Hostels", to: "/admin/hostels", icon: Building2 },
    { label: "Expenses", to: "/admin/expenses", icon: IndianRupee },
    { label: "Consumption", to: "/admin/consumption", icon: ListOrdered },
    { label: "Approvals", to: "/admin/approvals", icon: ShieldCheck },
    { label: "Analytics", to: "/admin/analytics", icon: BarChart3 },
    { label: "Ledger", to: "/admin/ledger", icon: FileBarChart2 },
    { label: "Users", to: "/admin/users", icon: Users },
  ],
  dean: [
    { label: "Overview", to: "/admin", icon: LayoutDashboard },
    { label: "Approvals", to: "/admin/approvals", icon: ShieldCheck },
    { label: "Analytics", to: "/admin/analytics", icon: BarChart3 },
    { label: "Ledger", to: "/admin/ledger", icon: FileBarChart2 },
  ],
  warden: [
    { label: "Overview", to: "/admin", icon: LayoutDashboard },
    { label: "Approvals", to: "/admin/approvals", icon: ShieldCheck },
    { label: "Analytics", to: "/admin/analytics", icon: BarChart3 },
  ],
};
