const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema(
  {
    month: {
      type: String,
      required: [true, 'Month is required (format: Mon-YYYY)'],
      match: [
        /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-\d{4}$/,
        'Month must be in Mon-YYYY format',
      ],
    },
    hostelId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Hostel',
      required: [true, 'Hostel is required'],
    },
    status: {
      type: String,
      enum: {
        values: ['draft', 'submitted', 'warden_approved', 'dean_approved'],
        message: 'Invalid status',
      },
      default: 'draft',
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by is required'],
    },
    submittedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    submittedAt: {
      type: Date,
      default: null,
    },
    approvedByWarden: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    wardenApprovedAt: {
      type: Date,
      default: null,
    },
    wardenNotes: {
      type: String,
      default: '',
    },
    approvedByDean: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    deanApprovedAt: {
      type: Date,
      default: null,
    },
    deanNotes: {
      type: String,
      default: '',
    },
    totalExpenses: {
      type: Number,
      default: 0,
    },
    totalBilled: {
      type: Number,
      default: 0,
    },
    totalCollected: {
      type: Number,
      default: 0,
    },
    outstanding: {
      type: Number,
      default: 0,
    },
    hostelWiseBreakdown: [
      {
        hostelId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Hostel',
        },
        hostelName: {
          type: String,
          default: '',
        },
        totalBilled: {
          type: Number,
          default: 0,
        },
        totalStudents: {
          type: Number,
          default: 0,
        },
      },
    ],
    studentWiseSummary: [
      {
        studentId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Student',
        },
        studentCode: {
          type: String,
          default: '',
        },
        name: {
          type: String,
          default: '',
        },
        billAmount: {
          type: Number,
          default: 0,
        },
        paymentStatus: {
          type: String,
          default: 'pending',
        },
      },
    ],
    totalAmount: {
      type: Number,
      default: 0,
    },
    snapshot: {
      generatedAt: {
        type: Date,
        default: null,
      },
      expenses: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
      charges: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
      payments: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
      totals: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
    },
  },
  { timestamps: true }
);

// Unique index on hostel + month
reportSchema.index({ hostelId: 1, month: 1 }, { unique: true });
reportSchema.index({ month: 1, status: 1, hostelId: 1 });

module.exports = mongoose.model('Report', reportSchema);
