const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema(
  {
    month: {
      type: String,
      required: [true, 'Month is required (format: YYYY-MM)'],
      match: [/^\d{4}-\d{2}$/, 'Month must be in YYYY-MM format'],
    },
    hostelId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Hostel',
      required: [true, 'Hostel is required'],
    },
    status: {
      type: String,
      enum: {
        values: ['draft', 'submitted', 'warden_approved', 'dean_approved'],
        message: 'Invalid status',
      },
      default: 'draft',
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by is required'],
    },
    submittedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    submittedAt: {
      type: Date,
      default: null,
    },
    approvedByWarden: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    wardenApprovedAt: {
      type: Date,
      default: null,
    },
    wardenNotes: {
      type: String,
      default: '',
    },
    approvedByDean: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    deanApprovedAt: {
      type: Date,
      default: null,
    },
    deanNotes: {
      type: String,
      default: '',
    },
    billCount: {
      type: Number,
      default: 0,
    },
    totalAmount: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

// Unique index on hostel + month
reportSchema.index({ hostelId: 1, month: 1 }, { unique: true });

module.exports = mongoose.model('Report', reportSchema);
